import headshot from './self/headshot.jpg';
import ketomate from './logos/ketomate.png';
import hp from './logos/hp.png';
import reactLogo from './logos/reactLogo.svg';
import agechart from './portfolio/agechart.jpg';
import experiencechart from './portfolio/experiencechart.jpg';
import genderchart from './portfolio/genderchart.jpg';
import ketomate10k from './portfolio/ketomate10k.jpg';
import kmactive from './portfolio/km_active.jpg';
import kmadvanced from './portfolio/km_advanced.jpg';
import kmbodyfat from './portfolio/km_bodyfat.jpg';
import kmfaq from './portfolio/km_faq.jpg';
import kmhome from './portfolio/km_home.jpg';
import kmintro from './portfolio/km_intro.jpg';
import kmmenu from './portfolio/km_menu.jpg';
import kmresults from './portfolio/km_results.jpg';
import metricmedia from './portfolio/metricmedia.jpg';
import metricmediaspeed from './portfolio/metricmediaspeed.jpg';
import mylifter from './portfolio/mylifter.jpg';
import phoenixstone from './portfolio/phoenixstone.jpg';
import phoenixstonespeed from './portfolio/phoenixstone_speed.jpg';
import vanderhall from './portfolio/vanderhall.jpg';

export {headshot};
export {ketomate};
export {hp};
export {reactLogo};
export {agechart};
export {experiencechart};
export {genderchart};
export {ketomate10k};
export {kmactive};
export {kmadvanced};
export {kmbodyfat};
export {kmfaq};
export {kmhome};
export {kmintro};
export {kmmenu};
export {kmresults};
export {metricmedia};
export {metricmediaspeed};
export {mylifter};
export {phoenixstone};
export {phoenixstonespeed};
export {vanderhall};